### ISSUE TITLE
Behavior issues on RM2 Running 3.4.0.1784

### ISSUE THREAD

**Issue by csg33k** [isaacwisdom/RemarkableLamyEraser#56] opened 2023-06-08 13:57 UTC
I'm running the version listed above, about the only thing I've been able to get working is the press&hold to erase.

For simplicity's sake I ONLY have a single config value set in each case.  

I've ran the service manually to see the events (thank you for logging those).

```conf
press&hold                  erase-selection
```
I'm seeing the event being triggered in the RM2.

```sh
reMarkable: ~/ /usr/sbin/RemarkableLamyEraser
RemarkableLamyEraser 2.0.0
----------------------------------
Detected ReMarkable 2. Using Devices:
1. device file = /dev/input/event1
   device name = Wacom I2C Digitizer
2. device file = /dev/input/event2
   device name = pt_mt
----------------------------------
Using configuration file at /home/root/.config/LamyEraser/LamyEraser.conf
Line 35: Read trigger <press&hold> with effect <erase-selection>
----------------------------------
writing erase selection
writing erase selection off
writing erase selection
writing erase selection off

```

But the behavior is untagged.  

On the other hand if 

```conf
press&hold                  eraser
```

```sh
reMarkable: ~/ /usr/sbin/RemarkableLamyEraser
RemarkableLamyEraser 2.0.0
----------------------------------
Detected ReMarkable 2. Using Devices:
1. device file = /dev/input/event1
   device name = Wacom I2C Digitizer
2. device file = /dev/input/event2
   device name = pt_mt
----------------------------------
Using configuration file at /home/root/.config/LamyEraser/LamyEraser.conf
Line 35: Read trigger <press&hold> with effect <eraser>
----------------------------------
writing eraser
Activating ToolEraserRM2: writing eraser on
writing eraser
Deactivating ToolEraserRM2: writing pen on
```

**Comment by isaacwisdom** [comment] 2023-06-13 07:25
Should be (partially) fixed as of [8b8f163](https://github.com/isaacwisdom/RemarkableLamyEraser/commit/8b8f163fd09586e789cdf72c161d2144247ebfa5). Please try it out and let me know of any bugs!

**Comment by isaacwisdom** [comment] 2023-06-13 07:28
Duplicate of #44 , closing for tidiness

**Closed as completed by isaacwisdom** 2023-06-13 07:28 UTC

**Comment by csg33k** [comment] 2023-06-13 13:41
Thank you for quick turn around!
